import {
  type RepoPreparationArtifactPaths,
  repoPreparationArtifactPaths,
  repoPreparationSubmitToolName,
  repoPreparationToolDefinitions,
  repoPreparationToolNames,
} from "./repo-preparation-tool-definitions";

/**
 * Renders the provider-neutral Repo Preparation runtime module. It exposes
 * plain tool definitions and artifact handlers; Composition adapts these
 * definitions to a provider-specific tool API.
 */
export function createRepoPreparationToolRuntimeSource(
  input: {
    artifactPaths?: Partial<RepoPreparationArtifactPaths>;
  } = {},
): string {
  const artifactPaths = {
    ...repoPreparationArtifactPaths,
    ...input.artifactPaths,
  };
  return [
    'import { mkdir, readFile, writeFile } from "node:fs/promises"',
    'import { dirname } from "node:path"',
    "",
    `const dependencyInstallRequestPath = ${JSON.stringify(artifactPaths.dependencyInstallRequestPath)}`,
    `const preparationManifestPath = ${JSON.stringify(artifactPaths.preparationManifestPath)}`,
    `const preparationResultPath = ${JSON.stringify(artifactPaths.preparationResultPath)}`,
    `const validationRequestPath = ${JSON.stringify(artifactPaths.validationRequestPath)}`,
    `const validationResultPath = ${JSON.stringify(artifactPaths.validationResultPath)}`,
    "",
    "type ToolRuntime = {",
    "  args: Record<string, unknown>",
    "}",
    "type StageTool = {",
    "  acceptance: string",
    "  args: Record<string, { description: string; type: string; values?: string[] }>",
    "  description: string",
    "  execute: (runtime: ToolRuntime) => Promise<string>",
    "  name: string",
    "  precondition: string",
    "}",
    "",
    "function stringArg(runtime: ToolRuntime, name: string): string {",
    "  const value = runtime.args[name]",
    '  if (typeof value !== "string") throw new Error(`Tool argument ${name} must be a string.`)',
    "  return value",
    "}",
    "",
    "function nonEmptyStringArray(value: unknown): value is string[] {",
    '  return Array.isArray(value) && value.length > 0 && value.every((item) => typeof item === "string" && item.trim().length > 0)',
    "}",
    "",
    "function requiredNonEmptyStringArray(value: unknown): string[] {",
    '  if (!nonEmptyStringArray(value)) throw new Error("Failed Repo Preparation submissions require a non-empty blockers array of non-empty strings.")',
    "  return value",
    "}",
    "",
    "function optionalStringArray(runtime: ToolRuntime, name: string): string[] {",
    "  const value = runtime.args[name]",
    "  if (value === undefined) return []",
    '  if (!Array.isArray(value) || !value.every((item) => typeof item === "string")) {',
    "    throw new Error(`Repo Preparation ${name} must be an array of strings when supplied.`)",
    "  }",
    "  return value",
    "}",
    "",
    "function assertManifestPath(path: string) {",
    "  if (path !== preparationManifestPath) {",
    "    throw new Error(`Preparation manifest path must be ${preparationManifestPath}.`)",
    "  }",
    "}",
    "",
    "async function assertValidationPassed() {",
    "  let validation",
    "  try {",
    '    validation = JSON.parse(await readFile(validationResultPath, "utf8"))',
    "  } catch {",
    '    throw new Error("Run makeademo_validate_preparation and wait for a passing preparation preflight result before submitting.")',
    "  }",
    '  if (validation.status !== "succeeded") {',
    '    throw new Error("Latest MakeADemo preparation preflight has not passed. Fix the reported issues, run makeademo_validate_preparation again, and submit only after it passes.")',
    "  }",
    "  const validatedManifest = validation.manifest",
    '  const currentManifest = JSON.parse(await readFile(preparationManifestPath, "utf8"))',
    "  if (!validatedManifest || validatedManifest.demoCommand !== currentManifest.demoCommand || validatedManifest.url !== currentManifest.url || validatedManifest.workspaceId !== currentManifest.workspaceId) {",
    '    throw new Error("Preparation manifest file must match the latest passed preflight manifest for demoCommand, url, and workspaceId.")',
    "  }",
    "  return validatedManifest",
    "}",
    "",
    "export const repoPreparationToolDefinitions: StageTool[] = [",
    "  {",
    `    acceptance: ${JSON.stringify(repoPreparationToolDefinitions.dependencyRequestInstall.acceptance)},`,
    `    args: { command: { description: ${JSON.stringify(repoPreparationToolDefinitions.dependencyRequestInstall.argumentDescription)}, type: "string" } },`,
    `    description: ${JSON.stringify(repoPreparationToolDefinitions.dependencyRequestInstall.description)},`,
    "    async execute(runtime) {",
    '      const command = stringArg(runtime, "command")',
    "      await mkdir(dirname(dependencyInstallRequestPath), { recursive: true })",
    '      await writeFile(dependencyInstallRequestPath, JSON.stringify({ command }, null, 2), "utf8")',
    "      return `Requested backend dependency install: ${command}`",
    "    },",
    `    name: ${JSON.stringify(repoPreparationToolNames[0])},`,
    `    precondition: ${JSON.stringify(repoPreparationToolDefinitions.dependencyRequestInstall.precondition)},`,
    "  },",
    "  {",
    `    acceptance: ${JSON.stringify(repoPreparationToolDefinitions.validatePreparation.acceptance)},`,
    `    args: { manifestPath: { description: ${JSON.stringify(repoPreparationToolDefinitions.validatePreparation.argumentDescription)}, type: "string" } },`,
    `    description: ${JSON.stringify(repoPreparationToolDefinitions.validatePreparation.description)},`,
    "    async execute(runtime) {",
    '      const manifestPath = stringArg(runtime, "manifestPath")',
    "      assertManifestPath(manifestPath)",
    "      await mkdir(dirname(validationRequestPath), { recursive: true })",
    '      await writeFile(validationRequestPath, JSON.stringify({ manifestPath }, null, 2), "utf8")',
    '      return "Preparation preflight requested. Stop now and wait for MakeADemo preflight feedback before continuing."',
    "    },",
    `    name: ${JSON.stringify(repoPreparationToolNames[2])},`,
    `    precondition: ${JSON.stringify(repoPreparationToolDefinitions.validatePreparation.precondition)},`,
    "  },",
    "  {",
    `    acceptance: ${JSON.stringify(repoPreparationToolDefinitions.submitPreparationResult.acceptance)},`,
    '    args: { status: { description: "Whether Repo Preparation completed successfully.", type: "enum", values: ["succeeded", "failed"] }, blockers: { description: "Required when status is failed. User-actionable blockers.", type: "string[]" }, assumptions: { description: "Assumptions made during preparation.", type: "string[]" }, suggestedChanges: { description: "Suggested changes for failed preparation.", type: "string[]" } },',
    `    description: ${JSON.stringify(repoPreparationToolDefinitions.submitPreparationResult.description)},`,
    "    async execute(runtime) {",
    '      const status = stringArg(runtime, "status")',
    "      let manifest",
    '      if (status !== "succeeded" && status !== "failed") throw new Error("Repo Preparation status must be succeeded or failed.")',
    '      if (status === "succeeded") manifest = await assertValidationPassed()',
    '      const blockers = status === "failed" ? requiredNonEmptyStringArray(runtime.args.blockers) : undefined',
    "      await mkdir(dirname(preparationResultPath), { recursive: true })",
    '      const submission = status === "succeeded" ? { status, manifest } : { status, blockers, assumptions: optionalStringArray(runtime, "assumptions"), suggestedChanges: optionalStringArray(runtime, "suggestedChanges") }',
    '      await writeFile(preparationResultPath, JSON.stringify(submission, null, 2), "utf8")',
    "      return `Submitted Repo Preparation ${status} result.`",
    "    },",
    `    name: ${JSON.stringify(repoPreparationSubmitToolName)},`,
    `    precondition: ${JSON.stringify(repoPreparationToolDefinitions.submitPreparationResult.precondition)},`,
    "  },",
    "];",
    "",
  ].join("\n");
}
